
version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: postres-dev-pass
    ports:
      - 5432:5432
  app:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "go", "run", "main.go"]
    volumes:
      - .:/go/src/go-exercises/final_project
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db